### ISSUE TITLE
Create `/preview` route to support Text template previews

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/A2JDAT#94] opened 2021-12-06 19:30 UTC
This is related to the Viewer issue to allow Text template previews CCALI/a2jviewer#170

- [ ] add a `/preview` route and pair with a function to handle generating the html preview
- [ ] refactor any current functionality in the `/assemble` route/function to allow sharing of reused code for this new feature
- [ ] make sure the preview does not change or break the assemble code

**Comment by chasenlehara** [comment] 2021-12-06 23:11
Referencing this bit of logic: https://github.com/CCALI/a2jdat/blob/2669585d9bcc89ad720fabe8f94246b3b466c765/src/routes/assemble.js#L107

For this issue, do we need to only care about the `isSingleTemplateAssemble  === true` case, or will we need to support generating multiple previews for text templates and then combine them into a single preview?

**Comment by mitch-mitchel** [comment] 2021-12-07 01:30
Actually, the following `renderPdfForTextTemplates()` call was unified to always take an array of templates, even if only one. The single template test might only be doing that, putting a single template into an array. We could probably do a minor refactor that makes text templates an array earlier in `assemble` function, and remove that check.

As far as multiple text templates go, they are combined into a single html file, and I would expect that to be the final preview to the end user.  Basically stitch together any number of text templates into a single preview, possibly with a page break to white space separator between templates.

**Comment by chasenlehara** [comment] 2021-12-07 15:07
I think I follow what you’re saying in the first paragraph, thanks!

I’m a little confused about this though:

> As far as multiple text templates go, they are combined into a single html file, and I would expect that to be the final preview

I see this line that takes _templates_ and returns a PDF: https://github.com/CCALI/a2jdat/blob/2669585d9bcc89ad720fabe8f94246b3b466c765/src/routes/assemble.js#L133

It looks like it creates a PDF for each text template and then combines the PDFs: https://github.com/CCALI/a2jdat/blob/2669585d9bcc89ad720fabe8f94246b3b466c765/src/routes/assemble.js#L253-L265

It sounds like I should change this so when assembling, the current PDF behavior remains, but for preview, I should render the html pages and combine those. Is that right?

One more question: what’s the expected behavior for PDF templates? Should they just be ignored for preview, or should we include something in the html preview along the lines of “no preview available for this PDF template”?

**Comment by mitch-mitchel** [comment] 2021-12-08 01:08
I can't recall if each text template gets it's own page on the PDF - i feel like they just concat to fill up a page, until they spill over, but not %100 sure.

@JessicaFrank What do you think about PDF pages - should we have a message for them, or just ignore?

@chasenlehara you could have, for example:
texttemplate1
texttemplate2
pdftemplate1
texttemplate3
pdftemplate2

if we have a message for the pdf templates, that might be a feature, but might also be confusing - not sure.

**Comment by JessicaFrank** [comment] 2021-12-08 04:34
I'll ask our grant partners what they think. I feel like we need to at
least say other pages (the pdf templates) exist or the end user will be
surprised when they see the final package.

**Comment by chasenlehara** [comment] 2021-12-13 16:43
I’m going to run with something like this for now:

> At least one of your templates has a preview option, would you like to view it." That covers people with 1 text template, or people with potentially text + pdf combos that can't all be previewed. We aren't guaranteeing this is the final package, but offering an accessible preview when possible. (edited)

**Comment by chasenlehara** [comment] 2021-12-20 16:24
Remaining to-do list after the above MR gets merged in:

- [x] Return a message when there are no templates
- [x] Return a message when there are no active templates
- [x] Return a message when all the active templates have conditional logic
- [x] Update the html returned when there’s a PDF template

**Closed as completed** 2021-12-24 22:59 UTC
